version: '3.8'

services:
  app:
    build: .
    container_name: demo-app
    volumes:
      - .:/var/www/html
    expose:
      - 9000
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
